#!/bin/bash

#
# Internal Variables
#
PLATFORM=$(uname -s)
CWD=$(dirname ${BASH_SOURCE[0]})
OPTION_VERBOSE=0

source $CWD/arch/common.bash

case $PLATFORM in
    "Darwin")
        source $CWD/arch/darwin.bash
        ;;

    "Linux")
        if [ "$(os_name)" = "centos" ]; then
            source $CWD/arch/centos.bash
        elif [ "$(os_name)" = "ubuntu" ] || [ "$(os_name)" = "Ubuntu" ]; then
            source $CWD/arch/ubuntu.bash
        else
            echo "Unsupport Linux version $(os_name)"
            exit 1
        fi
        ;;

    *)
        echo "Unsupport PLATFORM -> $PLATFORM"
        exit 1
        ;;
esac

for opt in "$@"; do
    case $opt in
        --d) OPTION_VERBOSE=1 ;;
        --help|*)
            _usage
            exit 0
             ;;
    esac
done

_banner hi
_progress install_git git
_progress install_moreutils utils
_progress install_ag ag
_progress install_fzf fzf
_progress update_bashrc bash
_progress update_vimrc vim
_progress update_tmux tmux
_banner bye
